fallback to default on basename equals ext
silverstripe/silverstripe-assets pull request #495
Opened 2022-05-24 14:19 UTC by PawelSuwinski

Fixes silverstripe/silverstripe-assets#494

2022-05-25 08:51 UTC, dhensby requested changes
Thanks for this. I think we'd need a test for this to illustrate what it is fixing and to make sure there aren't any future regressions.

Can you also squash the 3 commits so the contributions are atomic, please.

2022-05-25 10:41 UTC, PawelSuwinski commented
Done.

Test case before fix:
```
# vendor/bin/phpunit vendor/silverstripe/assets/tests/php/FileNameFilterTest.php --filter Empty
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 80 ms, Memory: 22.00MB

There was 1 failure:

1) SilverStripe\Assets\Tests\FileNameFilterTest::testFilterWithEmptyString with data set #1 ('新しいファイル.jpg')
Failed asserting that 'jpg' ends with ".jpg".

/var/www/portal-app/portal/vendor/silverstripe/assets/tests/php/FileNameFilterTest.php:74
/var/www/portal-app/portal/vendor/sminnee/phpunit/phpunit:51
```

After fix:
```fcd3d7a350f8:/var/www/portal-app/portal# vendor/bin/phpunit vendor/silverstripe/assets/tests/php/FileNameFilterTest.php --filter Empty
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 78 ms, Memory: 22.00MB

OK (2 tests, 6 assertions)
```

2022-05-25 14:52 UTC, PawelSuwinski commented
> There are some linting errors which need to be fixed :)

Fixed

2022-05-30 01:02 UTC, GuySartorelli approved these changes

2022-05-30 01:04 UTC, merged