ENH Use the optimal file resolution strat by default
silverstripe/silverstripe-assets pull request #542
Opened 2023-02-23 21:37 UTC by GuySartorelli

## Parent issue
- https://github.com/silverstripe/silverstripe-assets/issues/541

2023-02-23 22:02 UTC, maxime-rainville requested changes
Good job picking this up. Your build failure will be legit because the unit test assumes that NaturalFileIDHelper will be there.

I would suggest either:
- removing the test or 
- updating the test to add the `NaturalFileIDHelper` back in. 

We still need to test that can validate that fallback resolution strategy still work. So option two might be preferable if there's no other test worrying about that possibility.

2023-02-23 22:11 UTC, GuySartorelli commented
> We still need to test that can validate that fallback resolution strategy still work

Do we though? This is a fallback on a legacy strategy for a legacy setup. No new projects will be using this configuration anyway. Any projects which have been around since this was needed (and therefore use this strategy for protected files) will throw deprecation warnings when they upgrade to 4.13 (see https://github.com/silverstripe/silverstripe-framework/issues/10692).

I would argue it's more appropriate to remove that from the test - if it _does_ work and people use it as a workaround then fine, we're not going out of our way to break it per se, but we shouldn't _actively_ support legacy fallbacks IMO.

That said, after reading this if you still think option 2 is preferable I'll do that.

2023-02-23 22:38 UTC, GuySartorelli commented
Nevermind, it turns out this test is kinda complex and it is easiest to just add that config back in for these tests.

2023-02-26 08:04 UTC, maxime-rainville approved these changes
LGTM

2023-02-26 08:04 UTC, merged