ENH Use appropriate formfields when auto-scaffolding files
silverstripe/silverstripe-assets pull request #618
Opened 2024-06-19 02:03 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/.github/issues/262

2024-06-19 02:04 UTC, GuySartorelli commented on src/File.php
> +    ): FormField {
This is necessary for the change to `Folder`.

2024-06-19 02:04 UTC, GuySartorelli commented on src/Folder.php
> +    }
You don't upload folders. This makes a lot more sense as a way to select folders.

2024-06-26 23:00 UTC, emteknetnz requested changes
Tested locally, works well, except that if I have a relation that is an Image::class, the auto-scaffolded upload field allows me to select regular files like PDFs which aren't images. Applies to has_one, has_many and many_many relations.

2024-07-01 22:55 UTC, GuySartorelli commented
When attempting to upload a PDF, it gives an error "Extension 'pdf' is not allowed"
![image](https://github.com/silverstripe/silverstripe-assets/assets/36352093/c8d66c4e-1b54-40d9-bfc5-59be6faa5805)

This is the pre-existing behaviour for has_one auto-scaffolded upload fields.

2024-07-02 04:52 UTC, emteknetnz commented
Weird, I must have mis-tested this, unable to replicate my issue

2024-07-02 05:00 UTC, emteknetnz approved these changes

2024-07-02 05:00 UTC, merged